FROM python:3.11-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy gateway code (make sure app.py runs on port 8000)
COPY app.py ./

# defaults (compose can also set these)
ENV EMPLOYEE_URL=http://lms-employee_service:5001
ENV MANAGER_URL=http://lms-manager_service:5002

EXPOSE 8000
CMD ["python", "app.py"]
