FROM python:3.11-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Ensure sqlite dir exists
RUN mkdir -p /app/instance && chmod 777 /app/instance

COPY app.py models.py extension.py ./

EXPOSE 5002
CMD ["python", "app.py"]
