FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Ensure instance dir for sqlite exists with proper perms
RUN mkdir -p /app/instance && chmod 777 /app/instance

# Copy service code
COPY app.py models.py extension.py ./

# Expose service port
EXPOSE 5001

# Run the service
CMD ["python", "app.py"]
